<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Тестовое задание</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            input {
                font-size: 24px;
                width: 100px;
            }

            table {
                margin: 20px auto;
            }
            td {
                border-style: solid;
                border-color: black;
                padding: 10px;
            }
        </style>
    </head>
    <body>
        <h1>Планоплан</h1>
        <div>Рассчет количества краски для площади</div>

        <form action="/">
            <label for="square_meters">площадь</label>
            <input type="number" step="0.1" name="square_meters"
                <?php if($squareMeters): ?>
                   value="<?= $squareMeters ?>"
                <?php endif ?>
            >м2
            <input type="submit" style="min-width: 200px" placeholder="Рассчитать">
        </form>
    <?php if($needLiters): ?>
        <table>
            <thead>
                <td>м2</td>
                <td>расход (л/м2)</td>
                <td>литров</td>
                <td>поставщик</td>
                <td>банки</td>
                <td>цена итого</td>
                <td>цена за м2</td>
                <td>остаток</td>
            </thead>
            <tr>
                <td><?= $squareMeters ?></td>
                <td><?= $consumption ?></td>
                <td><?= $needLiters ?></td>
                <td><?= $shopName ?></td>
                <td style="min-width: 100px"><?= print_r($goods,true) ?></td>
                <td><?= $totalPrice ?></td>
                <td><?= $pricePerMeter ?></td>
                <td><?= $remain ?></td>
            </tr>
        </table>
    <?php endif ?>
    </body>
</html>
